### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by will704** [serve-and-volley/atp-world-tour-tennis-data#11]
Hi,

I was wondering if you plan on adding a licence so others can use these programs and datasets? I think it would be very useful in my academic research but due to ethical reasons require a licence - simple examples you could add to the readme are here: https://creativecommons.org/share-your-work/

Thanks,
W

**Comment by serve-and-volley** [comment]
@wkingsnorth: Thank you for your question, and I have added a Creative Commons Attribution 4.0 International license to the README in the following commit: https://github.com/serve-and-volley/atp-world-tour-tennis-data/commit/f4d7f4bd181b4a9c740518a7a07f820ae334b54b

Let me know if you need anything else, thanks 🍻

**Comment by HBiSoft** [comment]
It doesn't really matter that the owner gives you the right to use this. It is against APT Tours terms and conditions, so you will not be able to release anything you get from the website.

`ATP owns or has the right to use all of the data, information, text, images, streaming media, video, sounds, icons, scores, rankings, statistics, and other content contained on this Website (the "Content"), and the copyrights and other intellectual property rights therein, unless otherwise noted. You may print one copy of the Content of this Website for your own personal, non-commercial use, but you may not make more than one copy of such Content, modify it in any way, distribute or transmit it to any other person or company, frame or otherwise display any of the Content of this Website on your own or any other Website, or make any other use of it. Such copying, modification, distribution, transmission, display, or use is a breach of this Agreement and infringes ATP's copyrights, copyrights licensed to ATP, rights of privacy and publicity of ATP members and others, trademark rights, and/or other rights owned or licensed by ATP.`

This is the case for most website's.

**Comment by will704** [comment]
@HBiSoft correct - I did not use this in the end & found other data in the end

**Comment by will704** [comment]
@serve-and-volley Thanks - it's always good to see peoples work be available for others to use
